inputs:
  beauty:
    mid: fonll_bhadron_nnpdfs_y05_13tev.txt
    fwd: fonll_bhadron_nnpdfs_y20_25_13tev.txt
  charm:
    mid: fonll_dzero_finebins_nnpdfs_y05_13tev.txt
    fwd: fonll_dzero_finebins_nnpdfs_y20_25_13tev.txt

frag_fracs:
  beauty:
    mid: 0.41
    fwd: 0.41
  charm:
    mid: 0.51
    fwd: 0.51

rebin_pt:
  beauty:
    enable: True
    ptlimits: [1., 2., 4., 6., 8., 10., 14., 23.5]
  charm:
    enable: True
    ptlimits: [0., 1., 1.5, 2., 2.5, 3., 3.5, 4., 5., 6., 7., 8., 9., 10., 12.]

legend:
  mid: "|#it{y}| < 0.5"
  fwd: "2.0 < #it{y} < 2.5"

output: fonll_bhadron_chadron_nnpdfs_y05_y20_25_13tev.root
